// Translations dictionary
window.COPY = {
  es: {
    nav: {
      services: "Servicios",
      process: "Proceso",
      work: "Trabajos",
      contact: "Contacto",
      cta: "Agendar llamada",
    },
    hero: {
      label: "01 / VALLARTA · MÉXICO",
      h1a: "Sitios web que venden",
      h1b: "mientras duermes",
      sub: "Diseñamos experiencias digitales para negocios que no se conforman con plantillas.",
      cta: "Agendar llamada",
      ctaSec: "Ver trabajos →",
      scroll: "DESPLAZA",
      ambient: "AMBIENT",
      ambientOff: "🔊 ACTIVAR SONIDO",
    },
    mani: {
      label: "02 / MANIFIESTO",
      h2a: "No diseñamos páginas.",
      h2b: "Diseñamos ",
      h2bi: "primeras",
      h2c: " impresiones.",
      body: "Cada pixel, cada animación, cada palabra está calculada para que tu cliente piense \u2018esto es serio\u2019 antes de leer la primera oración. Porque la confianza se gana en 3 segundos, no en 3 párrafos.",
    },
    svc: {
      label: "03 / SERVICIOS",
      title: "Tres formas de ganar.",
      sub: "Cada proyecto se construye a medida. Estos son los formatos.",
      cards: [
        {
          num: "01",
          title: "Páginas web",
          desc: "Sitios completos que posicionan tu marca como referente en tu industria. Diseño cinematográfico, velocidad de carga premium, SEO técnico incluido.",
          bullets: ["DISEÑO A MEDIDA", "HOSTING + DOMINIO", "SOPORTE 24/7"],
        },
        {
          num: "02",
          title: "Landing pages",
          desc: "Páginas de venta de una sola pantalla diseñadas para convertir. Cinematográficas, persuasivas, optimizadas para anuncios pagados.",
          bullets: ["COPYWRITING INCLUIDO", "ANIMACIONES GSAP", "A/B TESTING"],
        },
        {
          num: "03",
          title: "Bots a medida",
          desc: "Bots conversacionales para WhatsApp y web que atienden, califican y agendan clientes mientras tu equipo descansa. Personalizados a tu negocio.",
          bullets: ["WHATSAPP + WEB", "INTEGRACIÓN CRM", "ENTRENADO EN TU MARCA"],
        },
      ],
      examples: "VER EJEMPLOS →",
    },
    proc: {
      label: "04 / PROCESO",
      title: "De la idea al lanzamiento. En 4 movimientos.",
      steps: [
        { num: "01", title: "Descubrir", desc: "Una llamada de 30 minutos donde entendemos tu negocio, tu cliente y tu meta. Sin compromiso." },
        { num: "02", title: "Diseñar",   desc: "Creamos el primer mockup visual usando IA y herramientas de diseño avanzadas. Iteramos hasta que digas \u2018es perfecto\u2019." },
        { num: "03", title: "Construir", desc: "Programamos el sitio con código limpio, animaciones cinematográficas y optimización SEO. Tiempo: 7-14 días." },
        { num: "04", title: "Lanzar",    desc: "Deploy en Vercel, configuración de dominio, conexión a WhatsApp y formularios. Te entregamos las llaves." },
      ],
    },
    port: {
      label: "05 / TRABAJO SELECCIONADO",
      title: "Cada proyecto, un universo.",
      hoverCta: "VER PROYECTO →",
      items: [
        { cat: "HOTEL BOUTIQUE · SAYULITA",       name: "Casa Marlen",     type: "Página web completa + sistema de reservas" },
        { cat: "RESTAURANTE · ZONA ROMÁNTICA",    name: "Olvera",          type: "Landing + menú interactivo" },
        { cat: "CLÍNICA ESTÉTICA · P. VALLARTA",  name: "Clínica Aurora",  type: "Landing + bot WhatsApp de agendamiento" },
      ],
    },
    cta: {
      label: "06 / EL SIGUIENTE PASO",
      qa: "¿Listo para una web ",
      qb: "que ",
      qbi: "trabaje",
      qc: " por ti",
      qmark: "?",
      sub: "Agenda una llamada gratuita de 30 minutos. Sin compromiso, sin venta agresiva.",
      btnCall: "Agendar llamada",
      btnWa: "WhatsApp",
      foot: "RESPONDEMOS EN MENOS DE 2 HORAS · LUN A SÁB · 9 A.M. — 7 P.M.",
    },
    foot: {
      tag: "Diseño y código desde Puerto Vallarta para el mundo.",
      est: "MX · ESTABLECIDO 2026",
      navLabel: "NAVEGAR",
      contactLabel: "CONTACTO",
      navLinks: ["Inicio", "Servicios", "Proceso", "Trabajos", "Contacto"],
      copy: "© 2026 vallartaweb · Hecho con obsesión en Puerto Vallarta",
      legal: "Política de Privacidad · Términos",
    },
  },
  en: {
    nav: {
      services: "Services",
      process: "Process",
      work: "Work",
      contact: "Contact",
      cta: "Book a call",
    },
    hero: {
      label: "01 / VALLARTA · MEXICO",
      h1a: "Websites that sell",
      h1b: "while you sleep",
      sub: "We craft digital experiences for businesses that refuse to settle for templates.",
      cta: "Book a call",
      ctaSec: "See our work →",
      scroll: "SCROLL",
      ambient: "AMBIENT",
      ambientOff: "🔊 ENABLE SOUND",
    },
    mani: {
      label: "02 / MANIFESTO",
      h2a: "We don't design pages.",
      h2b: "We design ",
      h2bi: "first",
      h2c: " impressions.",
      body: "Every pixel, every animation, every word is calculated so your client thinks \u2018this is serious\u2019 before reading the first sentence. Because trust is earned in 3 seconds, not in 3 paragraphs.",
    },
    svc: {
      label: "03 / SERVICES",
      title: "Three ways to win.",
      sub: "Every project is custom-built. These are the formats.",
      cards: [
        {
          num: "01",
          title: "Websites",
          desc: "Complete sites that position your brand as the reference in your industry. Cinematic design, premium load speed, technical SEO included.",
          bullets: ["CUSTOM DESIGN", "HOSTING + DOMAIN", "24/7 SUPPORT"],
        },
        {
          num: "02",
          title: "Landing pages",
          desc: "Single-screen sales pages built to convert. Cinematic, persuasive, optimized for paid traffic.",
          bullets: ["COPYWRITING INCLUDED", "GSAP ANIMATIONS", "A/B TESTING"],
        },
        {
          num: "03",
          title: "Custom bots",
          desc: "Conversational bots for WhatsApp and web that attend, qualify, and book clients while your team rests. Tailored to your business.",
          bullets: ["WHATSAPP + WEB", "CRM INTEGRATION", "TRAINED ON YOUR BRAND"],
        },
      ],
      examples: "SEE EXAMPLES →",
    },
    proc: {
      label: "04 / PROCESS",
      title: "From idea to launch. In 4 movements.",
      steps: [
        { num: "01", title: "Discover", desc: "A 30-minute call where we understand your business, your client, and your goal. No commitment." },
        { num: "02", title: "Design",   desc: "We build the first visual mockup using AI and advanced design tools. We iterate until you say \u2018it's perfect\u2019." },
        { num: "03", title: "Build",    desc: "We code the site with clean code, cinematic animations, and SEO optimization. Time: 7-14 days." },
        { num: "04", title: "Launch",   desc: "Deploy to Vercel, domain setup, WhatsApp & forms wired up. We hand you the keys." },
      ],
    },
    port: {
      label: "05 / SELECTED WORK",
      title: "Every project, a universe.",
      hoverCta: "VIEW PROJECT →",
      items: [
        { cat: "BOUTIQUE HOTEL · SAYULITA",       name: "Casa Marlen",     type: "Full website + reservation system" },
        { cat: "RESTAURANT · ZONA ROMÁNTICA",     name: "Olvera",          type: "Landing + interactive menu" },
        { cat: "AESTHETIC CLINIC · P. VALLARTA",  name: "Clínica Aurora",  type: "Landing + WhatsApp booking bot" },
      ],
    },
    cta: {
      label: "06 / WHAT'S NEXT",
      qa: "Ready for a website ",
      qb: "that ",
      qbi: "works",
      qc: " for you",
      qmark: "?",
      sub: "Book a free 30-minute call. No commitment, no hard sell.",
      btnCall: "Book a call",
      btnWa: "WhatsApp",
      foot: "WE REPLY IN UNDER 2 HOURS · MON—SAT · 9 A.M. — 7 P.M.",
    },
    foot: {
      tag: "Design and code from Puerto Vallarta for the world.",
      est: "MX · ESTABLISHED 2026",
      navLabel: "NAVIGATE",
      contactLabel: "CONTACT",
      navLinks: ["Home", "Services", "Process", "Work", "Contact"],
      copy: "© 2026 vallartaweb · Made with obsession in Puerto Vallarta",
      legal: "Privacy · Terms",
    },
  },
};
